on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      # Install global dependencies
      - run: npm ci

      # Install dependencies inside svelte/
      - run: npm ci
        working-directory: svelte

      # Build Tailwind
      - run: npm run build:tailwind

      # Build popui svelte package
      - run: npm run package
        working-directory: svelte

      # Publish to npm
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: svelte
          token: ${{ secrets.NPM_TOKEN }}
          ignore-scripts: false